kind: Service
apiVersion: v1
metadata:
  name: ahaz-outer
  namespace: ahaz
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 8080
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ahaz
    app.kubernetes.io/name: ahaz
